name: clang-tidy check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tidy-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Optionally generate compile_commands.json

    - uses: ZedThree/clang-tidy-review@v0.10.0
      id: review
      with:
        apt_packages: liblapack-dev
        config_file: '.clang-tidy'
        
    - if: steps.review.outputs.total_comments > 0
      run: exit 1